
//Liste des Interventins 
export const GET_INTERVENTIONS_REQUEST = 'GET_INTERVENTIONS_REQUEST';
export const GET_INTERVENTIONS_SUCCESS = 'GET_INTERVENTIONS_SUCCESS';
export const GET_INTERVENTIONS_FAILURE = 'GET_INTERVENTIONS_FAILURE';
